In [85]:
import numpy as np
import pandas as pd
import joblib

In [86]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [87]:
df = pd.read_csv('project4_waste_generation.csv')

In [88]:
df.head()

,Week_Start_Date,Neighborhood,Population_Density_per_km2,Number_of_Businesses,Avg_Household_Size,Market_Present,Industrial_Zone,Collection_Frequency_per_Week,Month,Weekly_Waste_Weight_kg
0,2020-01-06,Bambili,4432,432,8.3,0,0,1,1,2736.7
1,2020-01-13,Bambili,4403,428,8.4,0,0,1,1,2407.3
2,2020-01-20,Bambili,4360,427,8.3,0,0,1,1,2346.0
3,2020-01-27,Bambili,4373,433,8.4,0,0,1,1,2831.3
4,2020-02-03,Bambili,4352,426,7.7,0,0,1,2,2688.3

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Week_Start_Date                10000 non-null  object
 1   Neighborhood                   10000 non-null  object
 2   Population_Density_per_km2     10000 non-null  int64
 3   Number_of_Businesses           10000 non-null  int64
 4   Avg_Household_Size             10000 non-null  float64
 5   Market_Present                 10000 non-null  int64
 6   Industrial_Zone                10000 non-null  int64
 7   Collection_Frequency_per_Week  10000 non-null  int64
 8   Month                          10000 non-null  int64
 9   Weekly_Waste_Weight_kg         10000 non-null  float64
dtypes: float64(2), int64(6), object(2)
memory usage: 781.4+ KB

In [90]:
x = df.drop('Week_Start_Date', axis=1)
y = df['Weekly_Waste_Weight_kg']
x

,Neighborhood,Population_Density_per_km2,Number_of_Businesses,Avg_Household_Size,Market_Present,Industrial_Zone,Collection_Frequency_per_Week,Month,Weekly_Waste_Weight_kg
0,Bambili,4432,432,8.3,0,0,1,1,2736.7
1,Bambili,4403,428,8.4,0,0,1,1,2407.3
2,Bambili,4360,427,8.3,0,0,1,1,2346.0
3,Bambili,4373,433,8.4,0,0,1,1,2831.3
4,Bambili,4352,426,7.7,0,0,1,2,2688.3
...,...,...,...,...,...,...,...,...,...
9995,Abakwa,1350,15,7.0,1,0,1,9,952.9
9996,Abakwa,1330,21,7.1,1,0,1,9,954.8
9997,Abakwa,1355,22,7.0,1,0,1,9,1308.1
9998,Abakwa,1318,17,6.7,1,0,1,9,913.2
9999,Abakwa,1357,18,7.0,1,0,1,10,1022.5

In [91]:
X = x.iloc[:,1:-1]
X

,Population_Density_per_km2,Number_of_Businesses,Avg_Household_Size,Market_Present,Industrial_Zone,Collection_Frequency_per_Week,Month
0,4432,432,8.3,0,0,1,1
1,4403,428,8.4,0,0,1,1
2,4360,427,8.3,0,0,1,1
3,4373,433,8.4,0,0,1,1
4,4352,426,7.7,0,0,1,2
...,...,...,...,...,...,...,...
9995,1350,15,7.0,1,0,1,9
9996,1330,21,7.1,1,0,1,9
9997,1355,22,7.0,1,0,1,9
9998,1318,17,6.7,1,0,1,9
9999,1357,18,7.0,1,0,1,10

In [92]:
scaler = StandardScaler()

In [93]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training Set Shape: {X_train.shape}")
print(f"Testing Set Shape: {X_test.shape}")

Training Set Shape: (8000, 7)
Testing Set Shape: (2000, 7)

In [94]:
X_train_scaled = scaler.fit_transform(X_train)
x_test_scaled = scaler.transform(X_test)

In [95]:
model = LinearRegression()
model

LinearRegression()

In [97]:
model.fit(X_train_scaled, y_train)

LinearRegression()

In [98]:
model.intercept_

2105.3625625

In [99]:
model.coef_

array([577.73105388, 330.93175904,  44.63271351,  94.96270791,
       150.31727117,  -0.67083303, -45.97169966])

In [100]:
y_pred = model.predict(x_test_scaled)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [101]:
print(f"Model performance on Test Set:")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

Model performance on Test Set:
Mean Squared Error (MSE): 83428.72
R-squared (R2): 0.83